apiVersion: apps/v1
kind: Deployment
metadata:
  name: stylized-rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
        - name: app
          image: sahanaysubramanya/stylized-rag:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  type: LoadBalancer
  selector:
    app: rag
  ports:
    - port: 80
      targetPort: 8501
